
- hosts: deployment
  become: true
  tasks:
    - apt:
        update_cache : yes

    - name: Downloading certificates for docker
      apt:
          name:
            - ca-certificates
            - curl
            - gnupg
          state: present

    - apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
    
    - apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
        state: present

    - name: Downloading Docker
      apt:
          name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          state: present

    - service:
        name: docker
        state: started

    - user:
        name: ubuntu
        groups: docker
        append: yes

    - name: Create application directory
      file:
        path: /mytrader
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: '0755'

    - name: Copying Docker compose file
      copy:
          src: docker-compose.yaml
          dest: /mytrader/docker-compose.yaml

    - name: Pulling latest image from dockerhub
      command: docker compose pull
      args:
        chdir: /mytrader


    - name: running docker compose file
      command: docker compose up -d
      args:
        chdir: /mytrader

    - name: Installing nginx
      apt:
        name: nginx
        state: present
      

    - name: Starting nginx
      service:
          name: nginx
          state: started
          enabled: yes

    - name: Copy template
      template:
          src: myapp.conf.j2
          dest: /etc/nginx/sites-available/myapp

    - name: Deleting default file
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent

    - name: Linking this enabled site
      file:
          src: /etc/nginx/sites-available/myapp
          dest: /etc/nginx/sites-enabled/myapp
          state: link
    
    - name: restarting the server
      service:
          name: nginx
          state: reloaded
          
  
     